# Generated by Django 3.1.4 on 2021-01-30 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenselist',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
