# Generated by Django 3.1.4 on 2021-02-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expenselist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselist',
            name='category',
            field=models.CharField(choices=[(1, 'Groceries'), (2, 'Trips and Eating outs'), (3, 'Hobbies/Entertainment'), (4, 'Fixed Expenses'), (5, 'others')], default=5, max_length=100),
        ),
    ]
