# Generated by Django 3.1.4 on 2021-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20210201_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselist',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Trips and Eating outs', 'Trips and Eating outs'), ('Hobbies/Entertainment', 'Hobbies/Entertainment'), ('Fixed Expenses', 'Fixed Expenses'), ('others', 'others')], default='others', max_length=100),
        ),
    ]
