# Generated by Django 3.1.4 on 2021-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20210201_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselist',
            name='category',
            field=models.CharField(choices=[('Groceries and Eatables', 'Groceries and Eatables'), ('Trips and Eating outs', 'Trips and Eating outs'), ('Hobbies/Entertainment', 'Hobbies/Entertainment'), ('Fixed Expenses', 'Fixed Expenses'), ('others', 'others')], default='others', max_length=100),
        ),
    ]
